### ISSUE TITLE
addon does not have the right structure

### ISSUE THREAD

**Issue by gbaumgart** [owagner/kodi2mqtt#11]
Hi,
i tried installing the latest release zip over SMB in Settings->Addons->Install from-> ... It comes on 2 different Kodi 15.2 boxes (PC & Raspberry-PI) with 'addon does not have the right structure'. 

Is there a trick? 
thank you!

**Comment by 2Zero** [comment]
@gbaumgart have you tried the zip from [here](https://github.com/owagner/kodi2mqtt/releases/download/v0.9/mqtt_addon.zip)

**Comment by gbaumgart** [comment]
yup, i did. i even tried to re-zip it again but no. i tried on ubunut-64 and OSMX for RPI.

**Comment by owagner** [comment]
I have just tested the v0.10 autobuild (https://github.com/owagner/kodi2mqtt/releases/download/v0.10/mqtt_addon.zip) and it installed fine both locally and via SMB on a Win10 (x64) system. I've previously installed the autobuilds on Ubuntu 14.04 x64 and Raspbian installs without problems.

Is it perhaps somehow possible that the archive was modified during download?

**Comment by gbaumgart** [comment]
Hi, the last link worked! I didn't use a download-manager or similar. Weird thing. 

Ok, thanks Olli and 2Zero!
