### ISSUE TITLE
player_type removed?

### ISSUE THREAD

**Issue by MehrCurry** [owagner/kodi2mqtt#18]
Hi,

i have a new kodi box and installed version 0.12 of your addon. The playbackstate topic does not include playertype any more, allthough the documentations says it should be there.

{ "topic": "kodi/status/playbackstate", "payload": "1", "qos": 0, "retain": false, "_msgid": "b5aa43f0.4a55c" }

Did i miss something?

**Comment by owagner** [comment]
This looks weird. The payload should never be just "1", but a JSON encoded object. From what is the above pasted output?

**Comment by owagner** [comment]
Verified that it wfm on both 0.12 and 0.13 on Jarvis 16.1 / Win32

**Comment by MehrCurry** [comment]
Thank you Oliver. I will give the new version a try. I am a bit busy this time, so for now you may close this topic.

Guido
