### ISSUE TITLE
Add on fails with Amazon Fire TV

### ISSUE THREAD

**Issue by edycus** [owagner/kodi2mqtt#19]
Do you know if the add on will work if Kodi is loaded on my Amazon Fire device? The requirement for Eclipse Paho for Python I am guessing is not installed on the Amazon fire device.

**Comment by owagner** [comment]
The Eclipse Paho library is actually included in the distribution, so that shouldn't be a showstopper.

I have no way to test the addon on a FireTV; **do** you actually get an error?

**Comment by MehrCurry** [comment]
I tried it a few month ago and it worked for me on the atv.

**Comment by chaosblog** [comment]
I tried it with the Fire TV and the Fire TV Stick - both works fine with the latest release.
