### ISSUE TITLE
Track Type im Playback State?

### ISSUE THREAD

**Issue by MehrCurry** [owagner/kodi2mqtt#2]
Hallo Oliver,

irgendwie spielst du mit den gleichen Sachen rum wie ich. Habe eben nach kodi und mqtt gesucht und schon wieder deine Arbeit gefunden.

Funktioniert perfekt ... und auf Anhieb.

Einen kleinen Erweiterungswunsch hätte ich ... ich nutze das Plugin, um je nach PlayBack State meine Philips Hue zu steuern - allerdings wünsche ich mir eine Unterscheidung nach Musik und Video. Kurz nach dem PlayBack State kommen ja die Details, da steht bei Musik der type:"Song" drin, aber ich brauch den Type im State Packet, eben auch am Ende und bei Pause um das Licht bei Filmen wieder hochzufahren.

Ich hab schon geschaut, ob ich das selber irgendwie reinkriege ... aber Python ist eine der wenigen Sprachen, mit denen ich noch gar nix gemacht habe.

Viele Grüße

Guido

**Comment by owagner** [comment]
Hm, logisch sind "Play state" und "Playing item" eigentlich zwei paar Schuhe; ich weiss auch nicht, ob das "Playing Item" immer sofort nach dem Start des Players schon gefüllt ist (z.B. wenn es sich um einen Netzwerkstream handelt und der Player noch gar nicht weiss, was er da spielt)

Ich könnte aber die "Player ID" und den Player-Typ mit in das State-Paket aufnehmen, das sollte Deinem Use-Case helfen:

{"id":1,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}

**Comment by MehrCurry** [comment]
Ja, ich kann deine Argumentation verstehen. Die Alternative wäre, in Node-RED den State als context.global.kodi.item zu speichern und hinterher nach zu sehen, was da gerade gestoppt oder pausiert wurden.

Die vorgeschlagene Lösung ist doch ein schöner Kompromiss.

**Comment by MehrCurry** [comment]
Oops ... ich dachte "close window"

**Comment by MehrCurry** [comment]
Ok, ich sehe gerade, dass du nur eine ganz dünne Adapterschicht über das JSON RPC API gelegt hast und im Prinzip nur die JSON Antwort von Kodi weiter reichst.

Dann macht das in der Tat wenig Sinn, an der Semantik rumzufummeln. Ich werd mir was anderes überlegen.

Trotzdem Danke

**Comment by owagner** [comment]
Jein; diverse der Datenabfragen sind durchgeleitet JSON, das Event-Handling kommt aber aus dem klassischen Python-Addon-API.

**Comment by owagner** [comment]
Ich hab es nun einfach mal so implementiert
