### ISSUE TITLE
Feature request: More info in json when playing TV series

### ISSUE THREAD

**Issue by blddk** [owagner/kodi2mqtt#20]
In the kodi_details we get the info about if it is a movie or episode, but when playing an episode, I would like to also get the title of the tv series playing, and season and episode number.

As it is right now, there is only info about what the episode name is.

**Comment by vizonyc** [comment]
- 1 for me also using it with openhab and it works perfectly for me except for that

**Comment by NovaGL** [comment]
This is easy to fix. Maybe I should do a pull request.

Change line 116 in service.py to this

``
res=sendrpc("Player.GetItem",{"playerid":activeplayerid,"properties":["showtitle","season","episode","imdbnumber","title","streamdetails","file","thumbnail","fanart"]})
``
