### ISSUE TITLE
Kein Playback State mehr

### ISSUE THREAD

**Issue by MehrCurry** [owagner/kodi2mqtt#3]
Hallo Oliver,

danke, dass du dich der Änderung angenommen hast. Ich bekomme mit der neuen Version allerdings gar keinen Playback State mehr, beim Starten einer Datei :(

Folgende Meldungen erhalte ich nun:

```
{"kodi_playbackdetails": {"subtitleenabled": true, "currentaudiostream": {"index": 0, "name": "Stereo", "language": "und", "channels": 2, "codec": "aac", "bitrate": 0}, "repeat": "off", "currentsubtitle": {}, "speed": 1}, "kodi_state": "started", "kodi_playertype": "video", "val": 1, "kodi_playerid": 1}
30.7.2015, 06:40:51[9773c75.f688c38]
kodi/status/title : [msg.payload] : string
{"kodi_details": {"title": "", "streamdetails": {"video": [{"stereomode": "", "width": 720, "codec": "avc1", "aspect": 1.25, "duration": 65, "height": 576}], "audio": [{"channels": 2, "codec": "aac", "language": "und"}], "subtitle": []}, "type": "unknown", "file": "smb://QNAP/Multimedia/video/Kurzfilme/BMW/An_old_trick_performed_by_the_BMW_S_1000_RR.mp4", "label": "An_old_trick_performed_by_the_BMW_S_1000_RR.mp4"}, "val": ""}
30.7.2015, 06:40:51[9773c75.f688c38]
kodi/status/progress : [msg.payload] : string
{"kodi_time": "00:00:00", "kodi_totaltime": "00:01:05", "val": 0.29999999999999999}
```

Am Ende kommt allerdings der Status:

```
{"kodi_state": "ended", "kodi_playertype": "video", "val": 0, "kodi_playerid": 1}
```

**Comment by owagner** [comment]
Könntest Du bitte einmal in das xbmc-Logfile schauen? Da muss irgendeine Exception sein.

**Comment by MehrCurry** [comment]
Im Log ist nichts auffällig. Allerdings ist der "Fehler" wohl auch eine Falschmeldung. Das erste Paket ist schon das gesuchte Status Paket. Es wird auch auf dem richtigen Topic gesendet: kodi/status/playbackstate : [msg.payload] : string

Der Objekttyp "kodi_playbackdetails" hat mich an einen Fehler glauben lassen. Ich weiß nicht, was die 0.5er Version als Objekttyp hatte ... auf jeden Fall funzt das jetzt sehr gut.

Wenn der Objekttyp in deinen Augen richtig ist, kannst du das Ticket gerne schließen.

Danke!

**Comment by owagner** [comment]
playbackstate ist richtig. Die Nachricht sollte in etwa so aussehen:

kodi/szhtpc/status/playbackstate {"kodi_state": "stopped", "kodi_playertype": "video", "val": 0, "kodi_player
id": 1}
