### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by fab33** [owagner/kodi2mqtt#6]
On startup, I have an error about the script (openelec). If I deactivate/reactivate, itworks fine.
My mosquitto broker is on another linux system (mosquitto host and kodi host are bothe wired on the same subnet ie 192.168.1.X).
Log : 
22:12:53 T:2961175616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.gaierror'>
                                            Error Contents: [Errno -2] Name or service not known
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.mqtt/service.py", line 227, in <module>
                                                startmqtt()
                                              File "/storage/.kodi/addons/service.mqtt/service.py", line 206, in startmqtt
                                                mqc=mqtt.Client()
                                              File "/storage/.kodi/addons/service.mqtt/lib/client.py", line 422, in **init**
                                                self._sockpairR, self._sockpairW = _socketpair_compat()
                                              File "/storage/.kodi/addons/service.mqtt/lib/client.py", line 267, in _socketpair_compat
                                                sock1.connect(("localhost", port))
                                              File "/odroid/build.OpenELEC-Odroid.C1.arm-5.0.6/Python-2.7.3/.install_pkg/usr/lib/python2.7/socket.py", line 223, in meth
                                            gaierror: [Errno -2] Name or service not known
                                            -->End of Python script error report<--
22:12:53 T:3043337152   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
22:12:54 T:3043337152   DEBUG: ------ Window Deinit (Pointer.xml) ------
22:12:54 T:2961175616    INFO: Python script stopped

**Comment by owagner** [comment]
Interesting, it's attempting to connect to localhost. I presume you have the correct MQTT broker configured in settings?

**Comment by fab33** [comment]
Yes my config is ok. When I restart my kodi system, I hav this error. After disable/enable the mqtt service, it works but only for the session. On next reboot, I have to make the procedure (disable/enable).

**Comment by fab33** [comment]
Any chance to have a patch for this issue ?

**Comment by owagner** [comment]
The version of the paho library which I've included seems to statically refer to "localhost" during initialization, a name which for some reason doesn't seem to resolve on your machine (I know nothing about OpenELEC, so I have no idea why that is so)

Could you please try to replace the lib/client.py module with this one:

http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.python.git/plain/src/paho/mqtt/client.py

and tell me whether this fixes the issue? The changelog suggests this:

# v1.0.2 - 2014-09-13
- Fix Client constructor for the case where "localhost" is unresolvable.
  Closes #439277.

Thanks.

**Comment by fab33** [comment]
Ok It works fine. Thank you for your help ! I let you close the issue.
